---
- hosts: all
  become: yes
  roles:
    - prerequisites

- hosts: loadBalancer
  become: yes
  vars_files:
    - vars/vars.yml
  roles:
    - load-balancer

- hosts: webApps
  become: yes
  roles:
    - web-app