---
- name: Create Web App Server with Nginx
  copy:
    src: "configs/web-app.conf"
    dest: "/etc/nginx/sites-enabled/web-app.conf"
    owner: root
    group: root
    mode: 0644

- name: Delete default Nginx Host
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  # when: remove_default_nginx_vhost == true

- name: Create index.html
  copy:
    src: "configs/index.html"
    dest: "/var/www/html/index.html"
    owner: root
    group: root

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded