---
loadBalancer:
  hosts:
    loadBalancer01:
      ansible_host: 52.64.228.185
      ansible_user: ubuntu
webApps:
  hosts:
    webApps01:
      ansible_host: 16.176.183.147
      ansible_user: ubuntu
    webApps02:
      ansible_host: 16.176.14.16
      ansible_user: ubuntu
    webApps03:
      ansible_host: 13.211.134.246
      ansible_user: ubuntu
all:
  children:
    loadBalancer:
    webApps:
      